### ISSUE TITLE
No pin drop in map for Malaysia address

### ISSUE THREAD

**Issue by engswee** [sapmentors/lemonaid#23]
My address is based in Malaysia, but I can't find any pin drop when in the "list everyone" view or even when the search filter has my name filtered.

![screen shot 2016-09-24 at 10 54 45 am](https://cloud.githubusercontent.com/assets/7220623/18805629/68e3b22e-8245-11e6-996c-4280753ef8ba.png)

**Comment by jpenninkhof** [comment]
Hey @engswee, we're able to geocode your address a bit better now. Can you verify your pin again?
If it's still not there or not accurate, please do feel free to re-open this ticket.

Also note that geocoding only takes place once every 24 hours due to rate limit contraints on the Google API that is taking care of the geocoding. Sorry for that.

**Comment by engswee** [comment]
Hi Jan

Unfortunately, the results are still the same. The pin is at Kuala Lipis, but it should be at Kuala Lumpur 

![pin](https://cloud.githubusercontent.com/assets/7220623/20377359/b36ecc76-acc9-11e6-8d76-ad89fa150088.png)

**Comment by gregorwolf** [comment]
I've maintained your address in my test system. Let's see if it is getting geocoded during the night job.

**Comment by gregorwolf** [comment]
Hi @engswee 
it seems that Google expects the State to be provided as "Wilayah Persekutuan Kuala Lumpur". I've updated your address information in lemonaid. Tomorrow the address should be correct.
Best regards
Gregor

**Comment by engswee** [comment]
Hi @gregorwolf 

This is spot on! The pin on the map is now correct after the State field has been updated. Didn't know Google needed it to be that exact!

Thanks!
