### ISSUE TITLE
Build error: cannot find symbol ODataJPAProcessorDefault

### ISSUE THREAD

**Issue by gregorwolf** [sapmentors/lemonaid#47]
In the moment the Travis Build fails with this error:

[ERROR] /home/travis/build/sapmentors/lemonaid/src/main/java/com/sap/mentors/lemonaid/odata/ODataJPAProcessor.java:[30,51] cannot find symbol 
  symbol:   class ODataJPAProcessorDefault
  location: package org.apache.olingo.odata2.jpa.processor.core

I think this is caused by the change [[OLINGO-1018] Removed obsolete ODataJPAProcessorDefault](https://github.com/apache/olingo-odata2/commit/03457349196c8788f7865e4478071c14d77c9ea3).

**Comment by jpenninkhof** [comment]
It's kind weird. Local builds work. And even previous succesful build on Travis now fail...

**Comment by larslanghammer** [comment]
I think the problem is caused by the change @gregorwolf mentioned. The dependencies pulled by maven are different between Travis and your local machine.

Travis: (Taken from the logs of the latest failed build):
Downloading: http://repo.maven.apache.org/maven2/org/apache/olingo/olingo-odata2-jpa-processor-api/2.0.8/olingo-odata2-jpa-processor-api-2.0.8.pom

My local machine while building with eclipse:
Downloading: http://dl.bintray.com/jpenninkhof/olingo/org/apache/olingo/olingo-odata2-jpa-processor-api/2.0.8/olingo-odata2-jpa-processor-api-2.0.8.pom

This seems to be a general problem of Travis ignoring custom repositories:
For Reference: https://github.com/travis-ci/travis-ci/issues/5805

#49 should fix the problem and bintray is now the Single Source of Truth for the olingo Dependencies.
